name: CD

on:
  release:
    types: [ published ]

  workflow_dispatch:
    inputs:
      version:
        description: "The version to publish"
        required: true
        type: string

defaults:
  run:
    shell: bash

env:
  TARGET_TAG: ${{ inputs.version && format('v{0}', inputs.version) || github.event.release.tag_name }}

jobs:
  nugetpush:
    runs-on: ubuntu-20.04
    steps:
      - name: Check Version Exists
        if: github.event_name == 'workflow_dispatch'
        run: >-
          curl
            -f
            -H "Accept: application/vnd.github+json"
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
            https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.TARGET_TAG }}

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TARGET_TAG }}

      - name: Fetch Cache
        uses: actions/cache@v2
        id: main-cache
        with:
          path: |
            **/obj
          key: ${{ runner.os }}-main-${{ hashFiles('**/*.csproj') }}

      - name: Pack Package
        run: dotnet pack ./src/PseudoLangwords/PseudoLangwords.csproj -p:Version="${TARGET_TAG:1}"

      - name: Publish Package
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./src/PseudoLangwords/bin/Release/*.nupkg
