name: CD

on:
  release:
    types: [ published ]

  workflow_dispatch:
    inputs:
      version:
        description: "The version to publish"
        required: true
        type: string

defaults:
  run:
    shell: bash

env:
  TARGET_TAG: ${{ inputs.version && format('v{0}', inputs.version) || github.event.release.tag_name }}

jobs:
  nugetpush:
    environment: NuGet
    runs-on: ubuntu-20.04
    steps:
      - name: Check Version Exists
        id: version_check
        if: github.event_name == 'workflow_dispatch'
        run: |-
          echo "::set-output name=version_json::$(curl \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.TARGET_TAG }})"

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.TARGET_TAG }}

      - name: Pack Package
        env:
          CHANGELOG: ${{ fromJSON(steps.version_check.outputs.version_json).body || github.event.release.body }}
        run: dotnet pack ./src/PseudoLangwords/PseudoLangwords.csproj -p:Version="${TARGET_TAG:1}" -p:PackageReleaseNotes="$CHANGELOG"

      - name: Publish Package
        run: dotnet nuget push "./src/PseudoLangwords/bin/Release/*.nupkg" -k "$NUGET_TOKEN" -s "https://api.nuget.org/v3/index.json"
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
